name: Build PR

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-linux-deb:
    name: Build DEB Package
    uses: ./.github/workflows/build-linux-deb.yml
    with:
      upload-artifacts: true
      
  build-linux-rpm:
    name: Build RPM Package
    uses: ./.github/workflows/build-linux-rpm.yml
    with:
      upload-artifacts: true
      
  build-windows:
    name: Build Windows
    uses: ./.github/workflows/build-windows.yml
    with:
      upload-artifacts: true
      
  build-macos:
    name: Build macOS
    uses: ./.github/workflows/build-macos.yml
    with:
      upload-artifacts: true
      
  build-android:
    name: Build Android
    uses: ./.github/workflows/build-android.yml
    with:
      upload-artifacts: true
      
  build-ios:
    name: Build iOS
    uses: ./.github/workflows/build-ios.yml
    with:
      upload-artifacts: true
